#ifndef PTRE_COMMON_COMMUNICATION_RDMA_RDMA_WRITER_H_
#define PTRE_COMMON_COMMUNICATION_RDMA_RDMA_WRITER_H_

namespace ptre {

class RdmaWriter {
  
}

}  // namespace ptre

#endif  // PTRE_COMMON_COMMUNICATION_RDMA_RDMA_WRITER_H_
