// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tcp_service.proto

#include "tcp_service.pb.h"
#include "tcp_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ptre {
namespace common {

static const char* Tcp_method_names[] = {
  "/ptre.common.Tcp/PullTensor",
  "/ptre.common.Tcp/PushTensor",
};

std::unique_ptr< Tcp::Stub> Tcp::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Tcp::Stub> stub(new Tcp::Stub(channel));
  return stub;
}

Tcp::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_PullTensor_(Tcp_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushTensor_(Tcp_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Tcp::Stub::PullTensor(::grpc::ClientContext* context, const ::ptre::common::PullTensorRequest& request, ::ptre::common::PullTensorResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PullTensor_, context, request, response);
}

void Tcp::Stub::experimental_async::PullTensor(::grpc::ClientContext* context, const ::ptre::common::PullTensorRequest* request, ::ptre::common::PullTensorResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PullTensor_, context, request, response, std::move(f));
}

void Tcp::Stub::experimental_async::PullTensor(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ptre::common::PullTensorResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PullTensor_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::ptre::common::PullTensorResponse>* Tcp::Stub::AsyncPullTensorRaw(::grpc::ClientContext* context, const ::ptre::common::PullTensorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ptre::common::PullTensorResponse>::Create(channel_.get(), cq, rpcmethod_PullTensor_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::ptre::common::PullTensorResponse>* Tcp::Stub::PrepareAsyncPullTensorRaw(::grpc::ClientContext* context, const ::ptre::common::PullTensorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ptre::common::PullTensorResponse>::Create(channel_.get(), cq, rpcmethod_PullTensor_, context, request, false);
}

::grpc::Status Tcp::Stub::PushTensor(::grpc::ClientContext* context, const ::ptre::common::PushTensorRequest& request, ::ptre::common::PushTensorResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PushTensor_, context, request, response);
}

void Tcp::Stub::experimental_async::PushTensor(::grpc::ClientContext* context, const ::ptre::common::PushTensorRequest* request, ::ptre::common::PushTensorResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PushTensor_, context, request, response, std::move(f));
}

void Tcp::Stub::experimental_async::PushTensor(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ptre::common::PushTensorResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PushTensor_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::ptre::common::PushTensorResponse>* Tcp::Stub::AsyncPushTensorRaw(::grpc::ClientContext* context, const ::ptre::common::PushTensorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ptre::common::PushTensorResponse>::Create(channel_.get(), cq, rpcmethod_PushTensor_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::ptre::common::PushTensorResponse>* Tcp::Stub::PrepareAsyncPushTensorRaw(::grpc::ClientContext* context, const ::ptre::common::PushTensorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ptre::common::PushTensorResponse>::Create(channel_.get(), cq, rpcmethod_PushTensor_, context, request, false);
}

Tcp::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Tcp_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Tcp::Service, ::ptre::common::PullTensorRequest, ::ptre::common::PullTensorResponse>(
          std::mem_fn(&Tcp::Service::PullTensor), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Tcp_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Tcp::Service, ::ptre::common::PushTensorRequest, ::ptre::common::PushTensorResponse>(
          std::mem_fn(&Tcp::Service::PushTensor), this)));
}

Tcp::Service::~Service() {
}

::grpc::Status Tcp::Service::PullTensor(::grpc::ServerContext* context, const ::ptre::common::PullTensorRequest* request, ::ptre::common::PullTensorResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Tcp::Service::PushTensor(::grpc::ServerContext* context, const ::ptre::common::PushTensorRequest* request, ::ptre::common::PushTensorResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ptre
}  // namespace common

